name: ServerPlugin1201
version: '${project.version}'
main: net.laserdiamond.serverplugin1201.ServerPlugin1201
api-version: '1.20'
authors: [ LaserDiamond52 ]
description: Server Plugin for Minecraft Server (1.20.1)

permissions:

  serverplugin1201.breakblock:
    description: Allows players to break blocks
  serverplugin1201.placeblock:
    description: Allows players to placee blocks
  serverplugin1201.harvestblock:
    description: Allows players to harvest blocks
  serverplugin1201.pickupitem:
    description: Allows players to pick up items
  serverplugin1201.dropitem:
    description: Allows players to drop items

  serverplugin1201.armorstand:
    description: Allows players to interact with armor stands
  serverplugin1201.interact:
    description: Allows players to interact with entities
  serverplugin1201.shearentity:
    description: Allows players to shear entities

  serverplugin1201.move:
    description: Allows players to move
  serverplugin1201.changemainhand:
    description: Allows players to change their mainhand
  serverplugin1201.swaphands:
    description: Allows players to swap between their main and offhand
  serverplugin1201.portaltravel:
    description: Allows players to travel through portals to other dimensions
  serverplugin1201.changegamemode:
    description: Allows players to change their gamemode

  serverplugin1201.chat:
    description: Allows players to chat
  serverplugin1201.executecommands:
    description: Allows players to execute commands

  serverplugin1201.giveitems:
    description: Allows players to give themselves items from this plugin

  serverplugin1201.skills:
    description: Allows players to view their skills
  serverplugin1201.stats:
    description: Allows players to see their stats
  serverplugin1201.tuningmenu:
    description: Allows players to use the skill menu
  serverplugin1201.resetskills:
    description: Allows player to reset skills
  serverplugin1201.mana:
    description: Allows players to manipulate their mana
  serverplugin1201.effect:
    description: Allows players to grant plugin effects to themselves/others

  serverplugin1201.experiencereset:
    description: Allows players to reset experience levels
  serverplugin1201.enchant:
    description: Gives access to the /pluginenchant command and its aliases

commands:

  plugineffect:
    description: gives a plugin effect to the specified player for a specified duration
    usage: /<command> <arg> <arg> <arg> <arg> <arg>
    permission: serverplugin1201.effect

  plugingive:
    description: gives a plugin item to the specified player
    usage: /<command> <arg> <arg>
    permission: serverplugin1201.giveitems
    aliases:
      - giveitem

  pluginenchant:
    description: enchants the player's mainhand with the specified enchantment at the specified level
    usage: /<command> <arg> <arg> <arg>
    permission: serverplugin1201.enchant

  stats:
    description: allows players to view their stats in a menu
    usage: /<command>
    permission: serverplugin1201.stats
    aliases:
      - viewstats

  refillmana:
    description: allows players to refill their mana instantly
    usage: /<command> <arg>
    permission: serverplugin1201.mana
