name: VenturePlugin
version: '${project.version}'
main: net.laserdiamond.ventureplugin.VenturePlugin
api-version: '1.20'
authors: [ LaserDiamond52 ]
description: Venture Plugin for Minecraft Server (1.20.1)

permissions:

  ventureplugin.breakblock:
    description: Allows players to break blocks
  ventureplugin.placeblock:
    description: Allows players to placee blocks
  ventureplugin.harvestblock:
    description: Allows players to harvest blocks
  ventureplugin.pickupitem:
    description: Allows players to pick up items
  ventureplugin.dropitem:
    description: Allows players to drop items

  ventureplugin.armorstand:
    description: Allows players to interact with armor stands
  ventureplugin.interact:
    description: Allows players to interact with entities
  ventureplugin.shearentity:
    description: Allows players to shear entities

  ventureplugin.move:
    description: Allows players to move
  ventureplugin.changemainhand:
    description: Allows players to change their mainhand
  ventureplugin.swaphands:
    description: Allows players to swap between their main and offhand
  ventureplugin.portaltravel:
    description: Allows players to travel through portals to other dimensions
  ventureplugin.changegamemode:
    description: Allows players to change their gamemode

  ventureplugin.chat:
    description: Allows players to chat
  ventureplugin.executecommands:
    description: Allows players to execute commands

  ventureplugin.giveitems:
    description: Allows players to give themselves items from this plugin

  ventureplugin.skills:
    description: Allows players to view their skills
  ventureplugin.stats:
    description: Allows players to see their stats
  ventureplugin.tuningmenu:
    description: Allows players to use the skill menu
  ventureplugin.resetskills:
    description: Allows player to reset skills
  ventureplugin.mana:
    description: Allows players to manipulate their mana
  ventureplugin.effect:
    description: Allows players to grant plugin effects to themselves/others

  ventureplugin.experiencereset:
    description: Allows players to reset experience levels
  ventureplugin.enchant:
    description: Gives access to the /pluginenchant command and its aliases

commands:

  plugineffect:
    description: gives a plugin effect to the specified player for a specified duration
    usage: /<command> <arg> <arg> <arg> <arg> <arg>
    permission: serverplugin1201.effect

  plugingive:
    description: gives a plugin item to the specified player
    usage: /<command> <arg> <arg>
    permission: serverplugin1201.giveitems
    aliases:
      - giveitem

  pluginenchant:
    description: enchants the player's mainhand with the specified enchantment at the specified level
    usage: /<command> <arg> <arg> <arg>
    permission: serverplugin1201.enchant

  stats:
    description: allows players to view their stats in a menu
    usage: /<command>
    permission: serverplugin1201.stats
    aliases:
      - viewstats

  refillmana:
    description: allows players to refill their mana instantly
    usage: /<command> <arg>
    permission: serverplugin1201.mana
